str_1 = input("Введите вашу строку: ")
str_1 = str_1.replace("a", "")
str_1 = str_1.replace("e", "")
str_1 = str_1.replace("i", "")
str_1 = str_1.replace("o", "")
str_1 = str_1.replace("u", "")
print("Преобразованная строка без гласных: ", str_1)